FROM debian:bullseye-slim

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    ca-certificates \
    git \
    git-lfs \
    ssh \
    make \
    wget \
    bzip2 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt
RUN wget --no-check-certificate -qO- https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 | tar xj
ENV PATH=${PATH}:/opt/gcc-arm-none-eabi-10.3-2021.10/bin

# By default, the Docker container is run with root user privileges.
# The root user typically has far more privileges than are required
# when running a custom application,
# and so creating a new user without root privileges provides better security.

# The overall command `useradd -ms /bin/bash apprunner` creates
# a new user account named "apprunner" with a home directory
# and sets the default shell to /bin/bash,
# allowing "apprunner" to use the Bash shell for command-line interactions.
RUN useradd -ms /bin/bash apprunner
USER apprunner

# Allow running git commands inside the container.
RUN git config --global --add safe.directory '*'

# Working directory during usage.
WORKDIR /project
